Add Flag -enum_org_prefixes_to_trim to Trim Enumeration Names
openconfig/ygot pull request #454
Opened 2020-09-16 22:40 UTC by wenovus

This is a very straightforward change that simply trims the organization prefixes whenever constructing the module part of the various enumerated names (`enumeration` and `identity`).

**It affects both uncompressed and compressed code**. I made this decision based on implementation simplicity -- it's easier to not have differentiated behaviour between the two modes. I have manually tested that `uexampleoc` continues to build and pass tests with this flag on, but didn't change the schema output as it looks unnatural given everything else is untrimmed.

2020-09-17 12:16 UTC, progressnerd approved these changes

2020-09-28 18:40 UTC, robshakir requested changes
Per my comments in the other PR - I'm not sure that this should apply to uncompressed schemas without a more robust way to deal with name clash sets, given that it will likely cause more. Let's discuss this.

2020-09-28 18:47 UTC, wenovus commented on ygen/codegen_test.go
> +
Need to remove this.

2020-10-02 17:34 UTC, robshakir approved these changes
Thanks for the changes here.

2020-10-02 18:22 UTC, merged