Add option for `RFC7951JSONConfig` to prepend module names only for irefs
openconfig/ygot pull request #631
Opened 2022-03-23 02:10 UTC by wenovus

I made it clear in the comments that this should be avoided for any standard implementation.

- Add new field `PrependModuleNameIdentityref` to `RFC7951JSONConfig`.
- Improve `appmodsJSON` doc comments.
- Change `appendModuleName` and similar names to `prependModuleNameIref` and similar names.
- Change all relevant instances of `appmod` and similar variables to `prependmod` and similar names.
- Change all relevant instances of "append" to "prepend" in doc comments when talking about prepending module names.

Tested:

Added test that `PrependModuleNameIdentityref` prepends the module name only for identityrefs.

2022-03-23 12:23 UTC, robshakir commented on ygot/render.go
> +	// AppendModuleNameIdentityref determines whether the module name is
```suggestion
	// PrependModuleNameIdentityref determines whether the module name is
```

2022-03-23 12:26 UTC, robshakir requested changes
LGTM, thanks Wen - one change for readability and a typo.

2022-03-23 17:19 UTC, wenovus commented on ygot/render.go
> +	sl, err := leaflistToSlice(field, args.rfc7951Config != nil && (args.rfc7951Config.AppendModuleName || args.rfc7951Config.PrependModuleNameIdentityref))
Done.

2022-03-24 22:10 UTC, robshakir approved these changes

2022-03-24 22:11 UTC, merged