More accurate enum naming and classification according to namesake type.
openconfig/ygot pull request #666
Opened 2022-05-12 23:27 UTC by wenovus

Currently for unions it uses the outer-most union for the name and the type classification, but it should rather use the namesake union instead.

The integration test changes are due to **unused enums** now removed from the generated file.

2022-05-13 15:05 UTC, robshakir approved these changes
Should this be behind a flag, since it potentially changes generated protobuf union names in downstream code? (I'm not sure whether it actually does within OpenConfig, but I think with these kind of changes - and what we've seen recently, we need to give users a way to opt-out of default changes for at least a couple of releases.) Did you regenerate the schemas?

Change seems logical to me though -- thanks.

2022-05-13 15:05 UTC, robshakir requested changes
Sorry, blocking comment on the flag above.

2022-05-14 00:05 UTC, wenovus commented
> Should this be behind a flag, since it potentially changes generated protobuf union names in downstream code? (I'm not sure whether it actually does within OpenConfig, but I think with these kind of changes - and what we've seen recently, we need to give users a way to opt-out of default changes for at least a couple of releases.) Did you regenerate the schemas?
> 
> Change seems logical to me though -- thanks.

I've put this PR after the backwards-incompatible enum flag removal PR such that it is clear there is no material changes in any output code.

2022-05-16 16:59 UTC, robshakir approved these changes
Approving based on the discussion in #667.

2022-05-24 02:42 UTC, merged