Change `IR.Enums` map's key to be a unique key instead of the enum's name.
openconfig/ygot pull request #669
Opened 2022-05-17 23:44 UTC by wenovus

Do this using the unique key created by `findEnumSet`. Otherwise there could be a name conflict (e.g. proto enum names) when looking up an enum.

If there is a conflict, then an error will be raised; however, this will never happen because even though the key space is currently separate within `enumSet`:
https://github.com/openconfig/ygot/blob/6f722a0cce2a47949294afa0c3f23b080d51e501/ygen/enumgen.go#L72-L75
Due to the way each key type is constructed, it means the three types' keys will never conflict.

2022-05-19 21:57 UTC, robshakir commented on ygen/enumgen.go
>  // followed by the CamelCase-ified version of the identity's name.
Update the doc comment here?

2022-05-19 22:03 UTC, robshakir requested changes

2022-05-24 04:05 UTC, wenovus commented on ygen/enumgen.go
> +func (s *enumSet) identityrefBaseTypeFromLeaf(idr *yang.Entry) (string, string, error) {
Done.

2022-05-24 04:05 UTC, wenovus commented on ygen/enumgen.go
>  // followed by the CamelCase-ified version of the identity's name.
Done.

2022-05-24 04:06 UTC, wenovus commented
@robshakir Pending comments are resolved.

2022-05-24 14:59 UTC, robshakir approved these changes
Thanks for the changes.

2022-05-24 19:33 UTC, merged