Run `gofmt` on the codebase.
openconfig/ygot pull request #722
Opened 2022-08-28 02:31 UTC by robshakir

Runs gofmt with `go version go1.19 darwin/amd64`.

2022-08-29 16:29 UTC, wenovus requested changes
Just some minor fixes needed since the new gofmt doesn't fix them all correctly:

https://go.dev/doc/comment
```
Analysis in 2022 found that only 3% of doc comments in public Go modules were reformatted at all by the draft Go 1.19 gofmt. Limiting ourselves to those comments, about 87% of gofmt’s reformattings preserved the structure that a person would infer from reading the comment; about 6% were tripped up by these kinds of unindented lists, unindented multiline shell commands, and unindented brace-delimited code blocks.
```

2022-08-29 16:29 UTC, wenovus commented on util/debug.go
>  // clock (container)
indent this line as well

2022-08-29 16:29 UTC, wenovus commented on util/reflect.go
> +//
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on util/reflect.go
> +//	  arbitrarily in the iteration function to carry state and results.
Same here, Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ygot/pathstrings.go
> +//
looks like erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/container.go
> +//	  into the supplied parent.
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/container.go
> +//	jsonTree is a JSON data tree which must be a map[string]interface{}.
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/leaf.go
> +//	schema points to the schema for the leaf type.
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/leaf.go
> +//	  Required if the unmarshaled type is an enum.
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/leaf_list.go
> +//	value is a gNMI TypedValue if enc is GNMIEncoding, represented as TypedValue_LeafListVal
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/list.go
> +//
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:29 UTC, wenovus commented on ytypes/list.go
>  func unmarshalList(schema *yang.Entry, parent interface{}, jsonList interface{}, enc Encoding, opts ...UnmarshalOpt) error {
Change to a [list](https://go.dev/doc/comment#lists) instead of the current erroneous indenting.

2022-08-29 16:32 UTC, robshakir commented on util/debug.go
>  // clock (container)
Fixed.

2022-09-01 21:45 UTC, wenovus approved these changes
@robshakir I made the fixes to my own reviews, PTAL not sure if you agree with them. It looks like we need this PR to enable new changes to the same files to be made to ygot.

2022-09-01 22:37 UTC, robshakir commented
@wenovus Apologies, didn't get a chance to look at this whilst out. That LGTM - I hadn't realised that `gofmt` had this issue with indenting like this.

2022-09-01 22:37 UTC, robshakir commented
I'm happy to merge if you are - thanks!

2022-09-01 23:18 UTC, merged